markdown: rdiscount
permalink: /:title/
url: http://biliangzu.cn
name: BILIANGZU.CN
author: biliangzu
qq: 188002720
email: 188002720@qq.com
duoshuo: biliangzu
beian: 浙ICP备12026616号
cnzz: 119959
weibo: kcxz8
github: biliangzu
pygments: true
safe: true
paginate: 20
about: "这里是biliangzu 的个人博客，创建于2013 年。开始使用了 Jekyll @ GitHub。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
